// Compacts data/ref/gd_2206_customSetup_objectTypes.csv — GameObject::customSetup from the
// 2.206 decompile, machine-interpreted for every id (tools/ref-run_customsetup2.py) — into
// src/physics/gameObjectTypes.ts. Types the game assigns outside customSetup (sawblades,
// most decoration created via createWithKey) show up as the default Solid with explicit=0.
import { readFileSync, writeFileSync } from "node:fs";
const text = readFileSync("data/ref/gd_2206_customSetup_objectTypes.csv", "utf8");
const [header, ...rows] = text.trim().split(/\r?\n/);
const cols = header.split(",");
const idx = (c: string) => cols.indexOf(c);
const out: string[] = [];
for (const row of rows) {
  // names may contain commas? they don't in this file, but be safe: split on the first 2 commas and the last 14.
  const parts = row.split(",");
  if (parts.length < cols.length) continue;
  const extra = parts.length - cols.length;
  const id = Number(parts[0]);
  const rest = parts.slice(2 + extra);
  const g = (c: string) => rest[idx(c) - 2];
  const type = Number(g("objectType"));
  const explicit = g("typeExplicitlySet") === "1";
  const w = Number(g("hitboxWidth_m_width")), h = Number(g("hitboxHeight_m_height")), r = Number(g("objectRadius"));
  const sx = g("spriteWidthScale"), sy = g("spriteHeightScale");
  const passable = g("isPassable") === "1";
  const fields = [`t: ${type}`];
  if (explicit) fields.push("e: 1");
  if (w > 0 || h > 0) fields.push(`w: ${w}, h: ${h}`);
  if (r > 0) fields.push(`r: ${r}`);
  if (sx && sy) fields.push(`sx: ${sx}, sy: ${sy}`);
  if (passable) fields.push("p: 1");
  out.push(`  [${id}, { ${fields.join(", ")} }],`);
}
writeFileSync("src/physics/gameObjectTypes.ts", `// Generated by tools/extract-game-types.ts from data/ref/gd_2206_customSetup_objectTypes.csv
// (GameObject::customSetup, GD 2.206 decompile). Do not edit.

/** GameObjectType enum values (Geode Enums.hpp). */
export const enum GOT {
  Solid = 0, Hazard = 2, InverseGravityPortal = 3, NormalGravityPortal = 4, ShipPortal = 5, CubePortal = 6,
  Decoration = 7, YellowJumpPad = 8, PinkJumpPad = 9, GravityPad = 10, YellowJumpRing = 11, PinkJumpRing = 12,
  GravityRing = 13, InverseMirrorPortal = 14, NormalMirrorPortal = 15, BallPortal = 16, RegularSizePortal = 17,
  MiniSizePortal = 18, UfoPortal = 19, Modifier = 20, Breakable = 21, SecretCoin = 22, DualPortal = 23,
  SoloPortal = 24, Slope = 25, WavePortal = 26, RobotPortal = 27, TeleportPortal = 28, GreenRing = 29,
  Collectible = 30, UserCoin = 31, DropRing = 32, SpiderPortal = 33, RedJumpPad = 34, RedJumpRing = 35,
  CustomRing = 36, DashRing = 37, GravityDashRing = 38, CollisionObject = 39, Special = 40, SwingPortal = 41,
  GravityTogglePortal = 42, SpiderOrb = 43, SpiderPad = 44, EnterEffectObject = 45, TeleportOrb = 46,
  AnimatedHazard = 47,
}

export interface GameObjectInfo {
  /** m_objectType after customSetup. */
  t: number;
  /** 1 when customSetup set the type explicitly; absent = default Solid (may be overridden elsewhere in the game). */
  e?: 1;
  /** m_width / m_height when customSetup set them (units). */
  w?: number;
  h?: number;
  /** m_objectRadius for circular hitboxes. */
  r?: number;
  /** Hazard sprite-scale factors: hitbox = sprite content size × (sx, sy). */
  sx?: number;
  sy?: number;
  /** m_isPassable (one-way platform). */
  p?: 1;
}

export const GAME_OBJECT_TYPES: ReadonlyMap<number, GameObjectInfo> = new Map<number, GameObjectInfo>([
${out.join("\n")}
]);
`);
console.log("entries", out.length);
