// Compacts opstic/gdclone's game-derived object table (data/ref/gdclone-object.json,
// ids <= 1911) into src/physics/gdcloneHitboxes.ts: hitbox shape per id, plus the
// set of ids the game gives no hitbox at all.
import { readFileSync, writeFileSync } from "node:fs";
interface Entry { texture?: string; hitbox?: { type: string; width?: number; height?: number; x?: number; y?: number; radius?: number }; color_type?: string; default_z_layer?: number }
const src = JSON.parse(readFileSync("data/ref/gdclone-object.json", "utf8")) as Record<string, Entry>;
const lines: string[] = [];
const none: number[] = [];
for (const [k, e] of Object.entries(src).sort((a, b) => Number(a[0]) - Number(b[0]))) {
  const id = Number(k);
  const h = e.hitbox;
  if (!h) { none.push(id); continue; }
  if (h.type === "Box") lines.push(`  [${id}, { type: "box", w: ${h.width}, h: ${h.height}, ox: ${h.x ?? 0}, oy: ${h.y ?? 0} }],`);
  else if (h.type === "Circle") lines.push(`  [${id}, { type: "circle", r: ${h.radius}, ox: 0, oy: 0 }],`);
  else if (h.type === "Slope") lines.push(`  [${id}, { type: "slope", w: ${h.width}, h: ${h.height} }],`);
}
const out = `// Generated by tools/extract-gdclone-hitboxes.ts from opstic/gdclone assets/data/object.json
// (hitboxes as the game assigns them in GameObject::customSetup, ids 1–1911). Do not edit.
import type { Hitbox } from "./types";

/** Every id ≤ 1911 that the game gives a hitbox, with its shape in units relative to the object centre. */
export const GDCLONE_HITBOXES: ReadonlyMap<number, Exclude<Hitbox, null>> = new Map<number, Exclude<Hitbox, null>>([
${lines.join("\n")}
]);

/** Ids ≤ 1911 the game knows but gives no hitbox (decoration, triggers, and a few specials handled by hand). */
export const GDCLONE_NO_HITBOX: ReadonlySet<number> = new Set<number>([
${none.reduce<string[]>((acc, id, i) => { if (i % 24 === 0) acc.push("  "); acc[acc.length - 1] += id + ", "; return acc; }, []).join("\n")}
]);

export const GDCLONE_MAX_ID = 1911;
`;
writeFileSync("src/physics/gdcloneHitboxes.ts", out);
console.log(`hitboxes: ${lines.length}, no-hitbox ids: ${none.length}`);
