// Writes src/triggers/catalogue.ts: every trigger object id, what the game
// calls it, and how heavily the official levels lean on it.
//
//   npx tsx tools/extract-triggers.ts
//
// Names come from data/ref/gd_2206_customSetup_objectTypes.csv, the machine
// interpretation of GameObject::customSetup from the 2.206 decompile. The ten
// ids it does not name are the 1.x colour triggers, which the game builds a
// different way; those are named here by hand and say so.
//
// The counts matter as much as the names. They are what says which triggers are
// worth getting exactly right — 1,376 pulse triggers across the levels earns
// more care than a single background-speed trigger — and what the coverage
// report weighs its percentage by.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ObjectsFile } from "../src/assets/objectTypes";
import { outPath } from "./paths";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const ASSETS = outPath("assets");

/**
 * The colour triggers customSetup does not name, by the channel each one
 * changes. [meas: usage and level range; the channels from
 *  EffectGameObject::customSetup :302332-302449 and objectFromVector
 *  :184244-184275]
 */
const LEGACY_NAMES: Record<number, string> = {
  29: "Color Trigger (BG, 1.x)",
  30: "Color Trigger (Ground, 1.x)",
  104: "Color Trigger (Line, 1.x)",
  105: "Color Trigger (Object, 1.x)",
  221: "Color Trigger (Col 1, 1.x)",
  717: "Color Trigger (Col 2, 1.x)",
  718: "Color Trigger (Col 3, 1.x)",
  743: "Color Trigger (Col 4, 1.x)",
  744: "Color Trigger (3DL, 1.x)",
  900: "Color Trigger (G2)",
  915: "Color Trigger (Line)",
};

interface Census {
  counts: Record<string, number>;
  perLevel: Record<string, number[]>;
}

function readCsvNames(): Map<number, string> {
  const lines = readFileSync(join(ROOT, "data", "ref", "gd_2206_customSetup_objectTypes.csv"), "utf8").trim().split(/\r?\n/);
  const head = lines[0].split(",");
  const idCol = head.indexOf("id");
  const nameCol = head.indexOf("name");
  const out = new Map<number, string>();
  for (const line of lines.slice(1)) {
    const cells = line.split(",");
    const id = Number(cells[idCol]);
    const name = (cells[nameCol] ?? "").trim();
    if (Number.isInteger(id) && name) out.set(id, name);
  }
  return out;
}

const objects = JSON.parse(readFileSync(join(ASSETS, "objects.json"), "utf8")) as ObjectsFile;
const census = JSON.parse(readFileSync(join(ROOT, "data", "census.json"), "utf8")) as Census;
const names = readCsvNames();

/** Which official levels place an id, so the catalogue can say where to look. */
const levelsOf = new Map<number, number[]>();
for (const [levelId, ids] of Object.entries(census.perLevel)) {
  for (const id of ids) {
    const list = levelsOf.get(id) ?? [];
    list.push(Number(levelId));
    levelsOf.set(id, list);
  }
}

const ids = Object.keys(objects.objects)
  .map(Number)
  .filter((id) => objects.objects[String(id)]?.k === "trigger")
  .sort((a, b) => a - b);

const rows = ids.map((id) => {
  const uses = census.counts[String(id)] ?? 0;
  const levels = (levelsOf.get(id) ?? []).sort((a, b) => a - b);
  const name = names.get(id) ?? LEGACY_NAMES[id] ?? "";
  return { id, name, uses, levels };
});

const used = rows.filter((r) => r.uses > 0);
const unnamed = rows.filter((r) => !r.name);
const body = rows
  .map((r) => {
    const name = r.name ? JSON.stringify(r.name) : '""';
    const levels = r.levels.length > 0 ? `[${r.levels.join(", ")}]` : "[]";
    return `  [${r.id}, { id: ${r.id}, name: ${name}, uses: ${r.uses}, levels: ${levels} }],`;
  })
  .join("\n");

const out = `// Generated by tools/extract-triggers.ts. Do not edit.
//
// Every trigger object id the table knows, with the name GameObject::customSetup
// gives it and how often the 27 official levels place it. Status lives next door
// in registry.ts, which is hand-written: this file is only what is true about
// the game, not what this port has done about it.

/** One trigger id as the game and the official levels describe it. */
export interface TriggerInfo {
  id: number;
  /** "" when the 2.206 table does not name it. */
  name: string;
  /** Placements across the 27 official levels. */
  uses: number;
  /** Official levels that place it. */
  levels: readonly number[];
}

/** ${rows.length} trigger ids; ${used.length} are used by the official levels. */
export const TRIGGER_CATALOGUE: ReadonlyMap<number, TriggerInfo> = new Map<number, TriggerInfo>([
${body}
]);

/** Placements of every trigger across the official levels. */
export const TOTAL_TRIGGER_PLACEMENTS = ${used.reduce((n, r) => n + r.uses, 0)};
`;

mkdirSync(join(ROOT, "src", "triggers"), { recursive: true });
writeFileSync(join(ROOT, "src", "triggers", "catalogue.ts"), out);
console.log(`${rows.length} trigger ids, ${used.length} used by the official levels`);
console.log(`${unnamed.length} unnamed: ${unnamed.map((r) => r.id).join(", ") || "none"}`);
console.log(`${used.reduce((n, r) => n + r.uses, 0).toLocaleString()} placements in total`);
